security:
    password_hashers:
        App\Entity\Actor:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Actor
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: group_list
            logout:
                path: app_logout
                target: group_list

    access_control:
        - { path: ^/group/create, roles: ROLE_USER }
        - { path: ^/group/\d+/edit, roles: ROLE_USER }
        - { path: ^/group/\d+/delete, roles: ROLE_USER }
        - { path: ^/group/\d+/discussion, roles: ROLE_USER, methods: [POST] }
        - { path: ^/group/\d+/add-discussion, roles: ROLE_USER }
        - { path: ^/group/\d+/invite, roles: ROLE_USER, methods: [POST] }
        - { path: ^/group/\d+/posts, roles: ROLE_USER, methods: [POST] }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/signup, roles: PUBLIC_ACCESS }
        - { path: ^/group, roles: PUBLIC_ACCESS }