controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# custom made
group_create:
    path: /group/create
    controller: App\Controller\GroupController::create

group_list:
    path: /groups
    controller: App\Controller\GroupController::list

group_edit:
    path: /group/{id}/edit
    controller: App\Controller\GroupController::edit

group_delete:
    path: /group/{id}/delete
    controller: App\Controller\GroupController::delete
    methods: POST
