parameters:
    weather_api_key: '%env(OPENWEATHERMAP_API_KEY)%'
    openai_api_key: '%env(OPENAI_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $weatherApiKey: '%weather_api_key%'
            $openAiApiKey: '%openai_api_key%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Repository\GroupRepository:
        arguments:
            $registry: '@doctrine'
            $logger: '@monolog.logger'
    App\Service\AISuggestionService:
        arguments:
            $groupRepository: '@App\Repository\GroupRepository'
            $entityManager: '@doctrine.orm.entity_manager'
    App\Twig\AppExtension:
        tags: ['twig.extension']
    App\Service\ImageGeneratorService:
        arguments:
            $openAiApiKey: '%openai_api_key%'
            $logger: '@logger'